### ISSUE TITLE
Include numeric required for Visual Studio 2015 Update 1

### ISSUE THREAD

**Issue by francoisgenolini** [rollbear/tachymeter#1]
For Visual Studio 2015 Update 1 native C++, the tachymeter example only compiles if the following include is added:

``` C++
#include <numeric>
```

this is for `accumulate` in line 147 of `benchmark.hpp`

**Comment by rollbear** [comment]
Added in commit ae8383905a6a0be03ec37a6940b83aed6720cd29. Sorry for the long delay.
